use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'

target 'ios-sdk-swift-examples' do

  pod 'IndoorAtlas', '3.0.0-beta2'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
