use_frameworks!
platform :ios, '12.0'

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/IndoorAtlas/CocoaPods-Specs.git'

target 'ios-sdk-swift-examples' do
  pod 'IndoorAtlas', '3.6.11'
  pod 'SVProgressHUD', '2.3.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
    end
  end
end
