use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'

target 'ios-sdk-swift-examples' do

  pod 'IndoorAtlas', '2.9.4'
  pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'

end
